-- MySQL Script generated by MySQL Workbench
-- Tue Apr 22 19:37:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autor` (
  `idautor` INT NOT NULL,
  `autor_nome` VARCHAR(45) NULL,
  `nacionalidade` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  PRIMARY KEY (`idautor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emprestimo` (
  `idemprestimo` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `livro_idlivro` INT NOT NULL,
  `data_emprestimo` DATE NULL,
  `data_dev_prev` DATE NULL,
  `data_dev_real` DATE NULL,
  `status` VARCHAR(45) NULL,
  `emprestimo_idemprestimo` INT NOT NULL,
  PRIMARY KEY (`idemprestimo`),
  INDEX `fk_emprestimo_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_emprestimo_livro1_idx` (`livro_idlivro` ASC) VISIBLE,
  INDEX `fk_emprestimo_emprestimo1_idx` (`emprestimo_idemprestimo` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_livro1`
    FOREIGN KEY (`livro_idlivro`)
    REFERENCES `mydb`.`livro` (`idlivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_emprestimo1`
    FOREIGN KEY (`emprestimo_idemprestimo`)
    REFERENCES `mydb`.`emprestimo` (`idemprestimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL,
  `usuario_nome` VARCHAR(45) NULL,
  `data_cadastro` DATE NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livro` (
  `idlivro` INT NOT NULL,
  `ano_publicacao` DATE NULL,
  `genero` VARCHAR(45) NULL,
  `descricao` TEXT NULL,
  `disponibilidade_iddisp` INT NOT NULL,
  `autor_idautor` INT NOT NULL,
  `disponibilidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idlivro`),
  INDEX `fk_livro_autor1_idx` (`autor_idautor` ASC) VISIBLE,
  CONSTRAINT `fk_livro_autor1`
    FOREIGN KEY (`autor_idautor`)
    REFERENCES `mydb`.`autor` (`idautor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emprestimo` (
  `idemprestimo` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `livro_idlivro` INT NOT NULL,
  `data_emprestimo` DATE NULL,
  `data_dev_prev` DATE NULL,
  `data_dev_real` DATE NULL,
  `status` VARCHAR(45) NULL,
  `emprestimo_idemprestimo` INT NOT NULL,
  PRIMARY KEY (`idemprestimo`),
  INDEX `fk_emprestimo_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_emprestimo_livro1_idx` (`livro_idlivro` ASC) VISIBLE,
  INDEX `fk_emprestimo_emprestimo1_idx` (`emprestimo_idemprestimo` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_livro1`
    FOREIGN KEY (`livro_idlivro`)
    REFERENCES `mydb`.`livro` (`idlivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_emprestimo1`
    FOREIGN KEY (`emprestimo_idemprestimo`)
    REFERENCES `mydb`.`emprestimo` (`idemprestimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
